# Generated by Django 3.1.2 on 2020-11-04 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('brands', models.CharField(max_length=100)),
                ('categories_tags', models.CharField(max_length=500)),
                ('nutriments', models.CharField(default='', max_length=10000)),
                ('nutrition_grade_fr', models.CharField(max_length=1)),
                ('product_name_fr', models.CharField(max_length=100, unique=True)),
                ('image_url', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('substitued', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_product_substitued', to='catalog.product')),
                ('substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_product_substitute', to='catalog.product')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('substitute', 'user')},
            },
        ),
    ]
